services:
  go-app:
    image: ubuntu:20.04
    container_name: monitor_testing_container
    volumes:
      - ../bin:/app
    command: ["/bin/bash", "-c", "apt update && apt install -y iproute2 net-tools procps && while true; do sleep 1000; done"]
    stdin_open: true
    tty: true
    ports:
      - 50051:50051
    networks:
      - app-network

networks:
      app-network:
        driver: bridge
