name: System monitoring platform

on:
  push:
    branches:
      - '**'

env:
  GO111MODULE: "on"

jobs:
  filter-changes:
    runs-on: ubuntu-latest
    outputs:
      client_changed: ${{ steps.filter.outputs.client }}
      monitoring_changed: ${{ steps.filter.outputs.monitoring }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Path Filter
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            client:
              - 'client/**'
            monitoring:
              - 'monitoring/**'

  lint-client:
    needs: filter-changes
    if: needs.filter-changes.outputs.client_changed == 'true'
    name: Lint Client
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Install golangci-lint manually
        run: |
          GOBIN=$PWD/golib/bin go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.62.2
        working-directory: ./monitoring

      - name: Add golib/bin to PATH
        run: echo "$PWD/golib/bin" >> $GITHUB_PATH
        working-directory: ./monitoring

      - name: Run make lint in client
        working-directory: ./client
        run: make lint

  lint-monitoring:
    needs: filter-changes
    if: needs.filter-changes.outputs.monitoring_changed == 'true'
    name: Lint Monitoring
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Install golangci-lint manually
        run: |
          GOBIN=$PWD/golib/bin go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.62.2
        working-directory: ./monitoring

      - name: Add golib/bin to PATH
        run: echo "$PWD/golib/bin" >> $GITHUB_PATH
        working-directory: ./monitoring

      - name: Run make lint in monitoring
        working-directory: ./monitoring
        run: make lint
