name: System monitoring platform

on:
  push:
    branches:
      - '**'

env:
  GO111MODULE: "on"

jobs:
  filter_changes:
    name: Filter changes
    runs-on: ubuntu-latest
    outputs:
      client_changed: ${{ steps.filter.outputs.client }}
      monitoring_changed: ${{ steps.filter.outputs.monitoring }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Filter changes
        id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            client:
              - 'client/**'
            monitoring:
              - 'monitoring/**'

      - name: Debug output
        run: |
          echo "Monitoring changed: ${{ steps.filter.outputs.monitoring_changed }}"
          echo "Type: $(typeof ${{ steps.filter.outputs.monitoring_changed }})"

  lint_client:
    runs-on: ubuntu-latest
    if: ${{ needs.filter_changes.outputs.client_changed }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run make lint in client
        run: make lint
        working-directory: client

  lint_monitoring:
    runs-on: ubuntu-latest
    if: ${{ needs.filter_changes.outputs.monitoring_changed }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run make lint in monitoring
        run: make lint
        working-directory: monitoring
