name: System monitoring platform

on:
  push:
    branches:
      - '**'

env:
  GO111MODULE: "on"

jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project:
          - { dir: "monitoring", path: "monitoring" }
          - { dir: "client", path: "client" }
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Get changes for ${{ matrix.project.dir }}
        id: changed_files
        uses: tj-actions/changed-files@v35
        with:
          files: ${{ matrix.project.path }}
          json: true

      - name: Set changed flag
        id: set_flag
        run: |
          # Если есть изменения — ставим флаг в true
          if [[ "${{ steps.changed_files.outputs.all_changed_files }}" != "" ]]; then
          echo "has_changes=true" >> "$GITHUB_OUTPUT"
          else
          echo "has_changes=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Debug outputs
        run: |
          echo "All changed files: ${{ steps.changed_files.outputs.all_changed_files }}"
          echo "Has changes: ${{ steps.set_flag.outputs.has_changes }}"

      - name: Go set up
        if: steps.set_flag.outputs.has_changes == 'true'
        uses: actions/setup-go@v3
        with:
          go-version: ^1.23

      - name: Run linter
        if: steps.set_flag.outputs.has_changes == 'true'
        run: make lint
        working-directory: ${{ matrix.project.dir }}

      - name: Run tests
        if: steps.set_flag.outputs.has_changes == 'true'
        run: make test
        working-directory: ${{ matrix.project.dir }}
