name: System monitoring platform

on:
  push:
    branches:
      - '**'

env:
  GO111MODULE: "on"

jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        projects:
          - { dir: "monitoring", path: "monitoring/**" }
          - { dir: "client", path: "client/**" }
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Get changes files
        id: changed_monitoring
        uses: tj-actions/changed-files@v35
        with:
          files: ${{ matrix.project.path }}/*

      - name: Debug changes
        run: |
            echo "Files changed: ${{ steps.changed_monitoring.outputs.files_changed }}"
            echo "All changed files: ${{ steps.changed_monitoring.outputs.all_changed_files }}"

      - name: Go set up
        if: steps.changed_monitoring.outputs.files_changed == 'true'
        uses: actions/setup-go@v3
        with:
          go-version: ^1.23

      - name: Run linter
        if: steps.changed_monitoring.outputs.files_changed == 'true'
        run: make lint
        working-directory: ${{ matrix.project.dir }}

      - name: Run tests
        if: steps.changed_monitoring.outputs.files_changed == 'true'
        run: make test
        working-directory: ${{ matrix.project.dir }}
