name: System monitoring platform

on:
  push:
    branches:
      - '**'

env:
  GO111MODULE: "on"

jobs:
  determine_changes:
    runs-on: ubuntu-latest
    outputs:
      client_changed: ${{ steps.check-changes.outputs.client }}
      monitoring_changed: ${{ steps.check-changes.outputs.monitoring }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check for changes in client/monitoring
        id: check-changes
        uses: tj-actions/changed-files@v34
        with:
          files: |
            client/**
            monitoring/**

  lint_client:
    runs-on: ubuntu-latest
    needs: determine_changes
    if: ${{ needs.determine_changes.outputs.client_changed == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run make lint in client
        run: make lint
        working-directory: client

  lint_monitoring:
    runs-on: ubuntu-latest
    needs: determine_changes
    if: ${{ needs.determine_changes.outputs.monitoring_changed == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run make lint in monitoring
        run: make lint
        working-directory: monitoring