name: System monitoring platform

on:
  push:
    branches:
      - '**'

env:
  GO111MODULE: "on"

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set_matrix.outputs.matrix }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Get all changed files
        id: changed_files
        uses: tj-actions/changed-files@v35
        with:
          files: |
            monitoring/
            client/
          json: true

      - name: Set project matrix
        id: set_matrix
        run: |
          CHANGED_FILES='${{ steps.changed_files.outputs.all_changed_files }}'

          PROJECTS=("monitoring" "client")

          MATRIX=()

          for project in "${PROJECTS[@]}"; do
            if echo "$CHANGED_FILES" | grep -q "\"$project/"; then
              MATRIX+=("{ \"dir\": \"$project\", \"path\": \"$project\" }")
            fi
          done

          joined=$(IFS=,; echo "[${MATRIX[*]}]")
          echo "matrix=$joined" >> "$GITHUB_OUTPUT"

  pipeline:
    needs: detect-changes
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.detect-changes.outputs.matrix) }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Debug changed project
        run: | 
          echo "Building project in directory: ${{ matrix.dir }}"

      - name: Go set up
        uses: actions/setup-go@v3
        with:
          go-version: ^1.23

      - name: Run linter
        run: make lint
        working-directory: ${{ matrix.dir }}

      - name: Run tests
        run: make test
        working-directory: ${{ matrix.dir }}