name: System monitoring platform

on:
  push:
    branches:
      - '**'

env:
  GO111MODULE: "on"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for changes in client
        id: check_client
        run: |
          git fetch origin main
          if git diff --name-only origin/main...HEAD | grep -q '^client/'; then
            echo "client changed"
            echo "true" >> $GITHUB_ENV
          else
            echo "false" >> $GITHUB_ENV
          fi

      - name: Check for changes in monitoring
        id: check_monitoring
        run: |
          git fetch origin main
          if git diff --name-only origin/main...HEAD | grep -q '^monitoring/'; then
            echo "monitoring changed"
            echo "true" >> $GITHUB_ENV
          else
            echo "false" >> $GITHUB_ENV
          fi

      - name: Run lint for client
        if: env.client == 'true'
        run: |
          cd client
          make lint

      - name: Run lint for monitoring
        if: env.monitoring == 'true'
        run: |
          cd monitoring
          make lint
