name: System monitoring platform

on:
  push:
    branches:
      - '**'

env:
  GO111MODULE: "on"

jobs:
  monitoring_jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Get changes files
        id: changed_monitoring
        uses: tj-actions/changed-files@v35
        with:
          files:
            monitoring/**

      - name: Go set up
        if: steps.changed_monitoring.outputs.files_changed == 'true'
        uses: actions/setup-go@v3
        with:
          go-version: ^1.23

      - name: Run linter
        if: steps.changed_monitoring.outputs.files_changed == 'true'
        run: make lint
        working-directory: monitoring

  client_jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Get changes files
        id: changed_monitoring
        uses: tj-actions/changed-files@v35
        with:
          files:
            client/**

      - name: Go set up
        if: steps.changed_monitoring.outputs.files_changed == 'true'
        uses: actions/setup-go@v3
        with:
          go-version: ^1.23

      - name: Run linter
        if: steps.changed_monitoring.outputs.files_changed == 'true'
        run: make lint
        working-directory: client